### ISSUE TITLE
explain how to get correct raw transaction

### ISSUE THREAD

**Issue by timekswaste** [CryptoXploit/bitcoin-key-compression#5]
run this script RawTX_RSZ.py
output : show r s1s2 z1,z2
but i got error what my mistake

https://tbtc.bitaps.com/raw/transaction/ff948290ff332aed8f0e5d767118a02e8671578c6775a333bb4ee4d6ccfcf639
i am enter raw tx i got error https://github.com/FoxxD3V/btc-rsz/blob/master/RawTX_RSZ.py
Traceback (most recent call last):
File "RawTX_RSZ.py", line 13, in
s = keyUtils.derSigToHexSig(m[1][:-2])
File "/home/runner/btc-rsz/keyUtils.py", line 32, in derSigToHexSig
x, s = ecdsa.der.remove_integer(s)
File "/usr/local/lib/python2.7/dist-packages/ecdsa/der.py", line 218, in remove_integer
raise UnexpectedDER("Negative integers are not supported")
ecdsa.der.UnexpectedDER: Negative integers are not supported

i know r s1s2
i need z1z2 value,please how to get z1z2 explain#mybadenglish

**Comment by amadhurkant** [comment]
The z is: ` c340c9ece755e54bf99c34386eb8e19befd76cb3ddd5b47a4d52be65fea05b6d`

There is no z2 as only one input is there.

**Comment by juragan69** [comment]
> znya adalah:` c340c9ece755e54bf99c34386eb8e19befd76cb3ddd5b47a4d52be65fea05b6d`
> 
> Tidak ada z2 karena hanya ada satu input.

how to get it
