### ISSUE TITLE
R-scanner.py is not calculating Values appropriately.

### ISSUE THREAD

**Issue by mozillafan** [CryptoXploit/bitcoin-key-compression#6]
## R-Scanner.py 
I scanned the following address: 1KkNDVahdSaCm8Rwm6APuLZhFBHGky7kmT [(address url)](https://www.blockchain.com/btc/address/1KkNDVahdSaCm8Rwm6APuLZhFBHGky7kmT)

The scanner returned: 
`Address 1KkNDVahdSaCm8Rwm6APuLZhFBHGky7kmT has 1 reused R value!` 
Okay that's good but when I checked the only spent transaction [trx url](https://www.blockchain.com/btc/tx/9dc07d170d4472c48d4d724017ce784b73b31a76f566755f90c924b71062c627) the input sig are as follows:

`Input:0
    r: 100e3dc7b32e20d952a31704beed8217413ca38206bf3c0281287c95e75c066d
 Input:1
     r: 504c0335566a7314d72239f785a3955b6f31a149f98715d801524c5a035cc927
 Input:2
     r: a597279c919e4553de8f67179a1d2fdc6584fde121f50c9f56ffcb1c37e5176022`

Correct me, if I have extracted wrong R values.

## R-Scanner.py
Another problem is this **R-Scanner.py** don't scan addresses greater than 50 txn.
Example: Inserting this ['12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S'](https://www.blockchain.com/btc/address/12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S) address will give me:
`SCAN ADDR
type address:  12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S
ADDRESS-R-SCAN: 
Data for pubkey: 12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S has   54  Txs

Fetching Txs from offset	0

Fetching Txs from offset	50
Traceback (most recent call last):
  File "R-Scaner.py", line 78, in <module>
    rscan(addr)
  File "R-Scaner.py", line 30, in rscan
    assert len(txs) == ntx
AssertionError`

So I can't scan addresses having 50+ txn.

## rscan.py
This simply doesn't work as **blockchain.info**'s new web address is **blockchain.com**, so I changed address in code to:
`urladdr = 'https://blockchain.com/address/%s?format=json&offset=%s'`
As all requests to **blockchain.info** are transferred to **blockchain.com** the output was same:
`urllib2.HTTPError: HTTP Error 404: Not Found`

This time I changed url address to:
`blockcount = urllib2.urlopen("https://chain.so/api/v2/address/BTC/").read()`
and removed following:
`blockstart = 170399
blockstart += 59711`

and the output was:
`Traceback (most recent call last):
  File "rscan.py", line 12, in <module>
    blockcount = urllib2.urlopen("https://chain.so/api/v2/address/BTC/").read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
`

So, please solve these errors.
Python Version: Python2.7.12

**Comment by Ango87** [comment]
@mozillafan  i have the same problem 😭

**Comment by Ango87** [comment]
@mozillafan what we should be doing, I found other programs in which I got the value of r but r1#r2 could not get the private key because of this problem

**Comment by mozillafan** [comment]
Mail me the TXID at 6gyosb6pz@mozmail.com
I will give you private key and 3/4 bitcoin of the address.
@Ango87

**Comment by Ango87** [comment]
@mozillafan Did the code work, did you get the r value

**Comment by couldnotfindone** [comment]
same problem , it doesn't fetch + 50 tx
