### ISSUE TITLE
api update please line 37

### ISSUE THREAD

**Issue by timekswaste** [CryptoXploit/bitcoin-key-compression#7]
https://github.com/CryptoXploit/bitcoin-key-compression/blob/main/rscan.py#L37

**Comment by mozillafan** [comment]
Change it: `urladdr = "https://blockchain.info/rawaddr/" + str(addr)`

**Comment by Ango87** [comment]
@mozillafan i got an error after changing the code

ADDRESS-R-SCAN:
Traceback (most recent call last):
  File "R-Scaner.py", line 72, in <module>
    rscan(addr)                                     File "R-Scaner.py", line 15, in rscan
    addrdata = json.load(urllib2.urlopen(urladdr % (addr, '0')))
TypeError: not all arguments converted during string formatting
